pipeline:
  identifier: Build_python_1728420111795
  name: Build python
  orgIdentifier: default
  projectIdentifier: Envi
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.vrquad
        repoName: python
  stages:
    - step:
        type: Run
        identifier: build_python_app
        name: Build Python App
        spec:
          shell: Sh
        command: |-
          echo "Welcome to Harness CI"
          python -m pip install --upgrade pip
          pip install  pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    command: |-
                      pip install flake8
                      flake8 .
                  timeout: ""
                  type: Run
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -e .
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: hello/world
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
